name: pipeline-tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: prefix-dev/setup-pixi@v0.10.1
        with:
          pixi-version: v0.76.2
          cache: true
      - run: pixi install --locked --all
      - run: pixi run forbidden-check
      - run: pixi run test
